baseURL = 'https://raghavian.github.io/blog/'
languageCode = 'en-uk'
title = 'Raghav Rants'
theme = 'PaperMod'
copyright = '© 2026 Raghavendra Selvan. Licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/).'

[params]
  # UI toggles
  ShowReadingTime = true
  ShowShareButtons = false
  ShowToc = true
  displayFullLangName = true
  comments = true

[build]
  # Ensure standard markdown compilation
  writeStats = true
